name: Android CI

on:
  push:
    branches:
      - '**'

permissions:
  contents: read # to fetch code (actions/checkout)
  checks: write
  security-events: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Git Checkout"
      uses: actions/checkout@v4
      with:
          submodules: true

    - uses: ./.github/actions/gradle-task-run
      with:
        gradle-tasks: "qa"
        reuse-configuration-cache: true
        gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
